spring:

  datasource:
    url: "jdbc:postgresql://localhost:5432/uhpoc"
    username: postgres
    password: Pass1word

  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        '[check_nullability]': true
        jdbc:
          '[time_zone]': UTC
      ddl-auto: update
        
        
server:
  port: 8090
    
   