spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/uhpocms
    username: postgres
    password: Pass1word

server:
  port: 8090
  
file:
  base-path: H:/uhpocmsUpload/course

