
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/UHPOC
    username: postgres
    password: Pass1word

  jpa:
    hibernate.ddl-auto: update
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
    show-sql:  true