
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/UHPOCMS
    username: postgres
    password: Pass1word

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql:  true