-- Table: public.admin_institution

-- DROP TABLE IF EXISTS public.admin_institution;

CREATE TABLE IF NOT EXISTS public.admin_institution
(
    institutionid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    createdby character varying(255) COLLATE pg_catalog."default" NOT NULL,
    createdon date NOT NULL,
    description character varying(255) COLLATE pg_catalog."default" NOT NULL,
    isactive boolean NOT NULL,
    modifiedby character varying(255) COLLATE pg_catalog."default" NOT NULL,
    modifiedon timestamp without time zone NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    picture character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT admin_institution_pkey PRIMARY KEY (institutionid),
    CONSTRAINT uk_r7p6t07od89mvlpktjjiqcdm6 UNIQUE (name)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.admin_institution
    OWNER to postgres;