spring:
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/uhpoc
    password: Pass1word
server:
  port: 8090


