spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: update
  show-sql: true
  hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  
  servlet:
     multipart:
      max-file-size: 800MB
      max-request-size: 500MB




spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/uhpocms
  username: postgres
  password: Pass1word

  jpa:
    hibernate.ddl-auto: update
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #generate-ddl: true
    show-sql:  true
    


server:
  port : 8092
  
  
file:
  base-path: D:/UHPOCMS
  
  
  spring.http:
    multipart.enabled=true