
spring:
  jpa:
    generate-ddl: true
    show-sql: true

    hibernate:
      ddl-auto: update
  
  
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    
server:
  port: 8090
  
 
 